export const strings = {
  appTitle: 'Rirekisho Maker',
  appSubtitle: '履歴書メーカー',

  step1Title: '基本情報',
  step1Sub: 'Informasi Dasar',
  step2Title: '学歴・職歴',
  step2Sub: 'Riwayat Pendidikan & Pekerjaan',
  step3Title: '免許・資格',
  step3Sub: 'Sertifikasi & Lisensi',
  step4Title: '希望欄',
  step4Sub: 'Preferensi & Keinginan',
  step5Title: 'プレビュー',
  step5Sub: 'Preview & Export',

  furiganaLabel: 'ふりがな',
  furiganaHint: 'Hiragana (あ), BUKAN katakana (ア)',
  fullNameLabel: '氏名 (Nama Lengkap)',
  fullNameHint: 'Tulis sesuai paspor. Warga asing biasanya katakana atau romaji',
  dobLabel: '生年月日 (Tanggal Lahir)',
  ageLabel: '満年齢',
  genderLabel: '性別',
  genderMale: '男 (Laki-laki)',
  genderFemale: '女 (Perempuan)',
  genderNone: '指定なし',

  postalCodeLabel: '郵便番号',
  prefectureLabel: '都道府県',
  addressLabel: '現住所 (Alamat)',
  addressFuriganaLabel: 'ふりがな',
  phoneLabel: '電話番号',
  emailLabel: 'メールアドレス',
  alternateContactLabel: '連絡先が現住所と異なる場合',

  historyAddEdu: '+ 追加 (学歴)',
  historyAddWork: '+ 追加 (職歴)',
  historyEdu: '学歴',
  historyWork: '職歴',
  historyEmpty: 'まだ履歴がありません',
  historyEmptyHint: '上記のボタンから追加してください',
  historyCategoryLabel: '区分',
  historyNameLabel: '学校名 / 会社名',
  historyFuriganaLabel: 'ふりがな',
  historyActionLabel: '区分',
  historyDetailLabel: '学部・部署・職種',
  historyCurrent: '現在学校・会社に在籍中（「現在に至る」行を追加）',
  historyOrderWarning: '日付の順序が逆になっています',

  licenseAdd: '+ 資格を追加',
  licenseNameLabel: '資格名',
  licenseIssuerLabel: '発行元',

  specialtiesLabel: '特技',
  hobbiesLabel: '趣味',
  motivationLabel: '志望動機',
  motivationHint: 'Hindari generik. Sebut nama perusahaan + alasan spesifik. 300-400 字 ideal',
  commuteLabel: '通勤時間',
  spouseLabel: '配偶者',
  dependentsLabel: '扶養家族（配偶者を除く）',
  requestsLabel: '本人希望記入欄',

  savePdf: 'PDFとして保存 / 印刷',
  downloadJson: 'JSON をダウンロード',
  importJson: 'JSON をインポート',
  reset: 'リセット',
  resetConfirm: '本当にリセットしますか？この操作は取り消せません。',
  next: '次へ',
  back: '← 戻る',
  preview: 'プレビュー',

  autoSaved: '自動保存済み',
  draftRestored: '下書きが復元されました',
  storageWarning: 'ストレージがいっぱいです。写真を削除してみてください',
  photoProcessing: '写真を処理中…',
  photoPlaceholder: '写真',
  photoChange: 'Ganti foto',
  photoRemove: 'Hapus',
  photoMaxSize: '画像は10MB以下にしてください',
  photoInvalidType: '画像ファイルを選択してください',

  privacyNote: 'Semua data (termasuk foto) tersimpan di browser Anda, tidak pernah dikirim ke server',
  sampleData: 'Coba dengan contoh',
  sampleDataConfirm: '現在のデータが上書きされます。よろしいですか？',
} as const;
